### ISSUE TITLE
Problem with "Remove startup level info"

### ISSUE THREAD

**Issue by gcerretani** [tango-controls/TangoDatabase#4]
If I select "Set startup level" -> "Remove startup level info" for any server in the astor control Panel, I get an error like this:

> Failed to query TANGO database (error=Incorrect integer value: '' for column 'pid' at row 1)
> .The query was: UPDATE device set exported=1,ior='',host='',pid='',version='0',started=NOW() where name LIKE 'dserver/snmp/test'

It seems to be related with some error in DataBase::db_export_device() in DataBase.cpp

I'm using TANGO 9.2.2, with ndbcluster as MySQL engine.

**Comment by bourtemb** [comment]
Hi Giovanni,
Thanks for the bug report.
It looks like this query is accepted on MySQL 5.5 but not on MySQL 5.7.
When looking deeper into the code, it appears there seems to be a bug in tangorb (jtango).
When trying to remove the startup level info, it seems astor is trying at some point to execute DbExportDevice command on the Tango Database server device with many empty arguments (ior,host,version).
To do that, it is using an export_device method taking a DbDevExportInfo object as parameter.
The problem seems to be that this DbDevExportInfo object does not have any field named pid.
This DbDevExportInfo object is transformed into a string array DbDevExportInfo.toStringArray() method, and this string array is passed as argin to DbExportDevice command.
The Database server is expecting the following arguments, in this order in the String array argin:
- Str[0] = device name
- Str[1] = CORBA IOR
- Str[2] = device server process host name
- Str[3] = device server PID or string "null"
- Str[4] = device server process version

The problem is it is not passing the arguments expected by the database server for this command.
DbDevExportInfo.toStringArray() method is creating a string array with the following cells:
- Str[0] = device name
- Str[1] = CORBA IOR
- Str[2] = device server process host name
- Str[3] = version
- Str[4] = "0"

There seems to be an inconsistency in jtango because there is another class named DeviceExportInfo which seems very similar to DbDevExportInfo class but taking into account correctly the pid parameter.
I will create an issue in jtango project to clarify all these points.

Thanks again for the bug report.
Reynald

**Comment by bourtemb** [comment]
I created this ticket on JTango project:
https://github.com/tango-controls/JTango/issues/30

**Comment by gcerretani** [comment]
Oh, nice. We're using MySQL 5.6.21.
Do I have any workaround for that?
Giovanni

**Comment by bourtemb** [comment]
I have a very good one: do not click on _Remove startup level info_ button!  ;-)
If you don't want your server to be controlled by astor and started automatically by the starter, simply select 
Controlled by Astor: No.
And click on OK, without clicking on _Remove startup level info_ button.
If what you want is really to get rid of it in astor and you really don't want to see this server listed in the not controlled server list, then it seems you can execute the following SQL statement:
`UPDATE device set host='' where server='YourServerName/instanceName';`
You can find your server name (with the proper case) by executing the following statement:
`SELECT DISTINCT server from device;`
Then restart the Starter on the host.

I think you can also simply (if you have enough hosts!) restart your server on a different host which is not managed by a Starter/astor.

Hoping this helps,
Reynald

**Comment by gcerretani** [comment]
Thank you a lot.
Giovanni

**Comment by t-b** [comment]
Issue seems resolved, please reopen if you disagree.
