### ISSUE TITLE
Interchangeable Database backend

### ISSUE THREAD

**Issue by Ingvord** [tango-controls/TangoDatabase#5]
Currently Tango Database backends by MySQL (MariaDB). It will be useful to provide a way to change backend for instance to PostgeSQL or MSSQL (in case of Windows) so that users could use native database backend for their deployment.

**Comment by t-b** [comment]
For smallish installations a sqlite database backend would also be nice.

**Comment by mliszcz** [comment]
I looked a bit into this problem recently. But my main focus was simplification and speedup of cppTango test suite and ability to quickly get a fresh tango system for development purposes so I made following assumption:
* we need to support at least MySQL and SQLite (including in-memory option for testing)
* we need to be able to statically link with all the dependencies (a single binary to have a tango system up and running)
* if we want to use SQLite backend, there should be no need for libmysqlclient.so presence in the system
* we must not degrade performance of existing MySQL deployments (so MySQL-specific stored procedures like `tango.ds_start` must stay - I don't have any numbers but judging from comments in the code this is done at database level for performance reasons)

For interchangeable backends the usual way to go is ODBC (on linux either unixODBC or iODBC), but due to ODBC design we cannot statically compile drivers inside the application. See: http://unixodbc.13851.n7.nabble.com/Building-a-single-static-unixODBC-application-Postgres-driver-td3507.html. We would also need some backend-awareness in the implementation because stored procedures are not supported in SQLite and we need fallback code.

Another option is to use a library that provides a common interface for different database access libraries. Some examples are https://www.sqlapi.com/ (unfortunately shareware) or https://github.com/SOCI/soci. SOCI looks really good and ticks all the boxes. Of course we still would need to work-around `ds_start` procedure.

Third option is to implement our own abstraction for accessing different backends. One benefit is that no extra dependency will be added to the database ds. But we will only support backends that we explicitly implement. This does not seem to be lot of work, we just need some very basic features, e.g. ability to run arbitrary query and retrieve a list of rows. Something like:
```cpp
class SQLiteBackend {
    template <typename ...Columns>
    std::vector<std::tuple<Columns...>> executeQuery(std::string query);
};
```

I'd go with the last approach (roll our own database access code) because no extra libraries are needed for that. But if we really need more backends than just MySQL and SQLite, I'd rather consider SOCI.

What do you think?

**Comment by mliszcz** [comment]
One more comment: good thing is that tango schema (create_db_tables.sql) can be loaded into SQLite with minor changes (and still can be compatible with MySQL).
